/* EXAMPLE */
let EXAMPLE_for_reference_only = {
  title: "Коммутативная алгебра",
  courses: [
    {
      id: 0,
      title: "Название Курса",
      description: "Кратко о курсе",
      course_category: "Раздел курса",
      lessons: [
        {
          title: "Название урока 1",
          lesson_type: "Тип урока",
          exercise: "Текст задания урока",
          file: "Файлик урока",
        },
        {
          title: "Название урока 2",
          lesson_type: "Тип урока",
          exercise: "Текст задания урока",
          file: "Файлик урока",
        },
        {
          title: "Название урока 3",
          lesson_type: "Тип урока",
          exercise: "Текст задания урока",
          file: "Файлик урока",
        },
        {
          title: "Название урока 4",
          lesson_type: "Тип урока",
          exercise: "Текст задания урока",
          file: "Файлик урока",
        },
      ],
      lessons_length: 4,
      rate: "Рейтинг курса",
      creator: "Имя создателя",
      price: "Цена курса",
      created_at: "Дата создания курса",
    },
  ],
};

let BRANCHES = [
  {
    title: "Коммутативная алгебра",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "История казахстана и прочего ",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Математический анализ",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Алгебра",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Аналитическая геометрия",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Линейная алгебра и геометрия",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Дискретная математика",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Математическая логика",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Дифференциальные уравнения",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Дифференциальная геометрия",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Топология",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Функциональный анализ и интегральные уравнения",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Теория функций комплексного переменного",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Уравнения в частных производных",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Теория чисел",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Теория вероятностей",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Мат.статистика",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Теория случайных процессов",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
  {
    title: "Вычислительная математика",
    courses: [
      {
        id: 0,
        title: "Название Курса",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 2",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
      {
        id: 0,
        title: "Название Курса 3",
        description: "Кратко о курсе",
        course_category: "Раздел курса",
        lessons: [
          {
            title: "Название урока 1",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 2",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 3",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
          {
            title: "Название урока 4",
            lesson_type: "Тип урока",
            exercise: "Текст задания урока",
            file: "Файлик урока",
          },
        ],
        lessons_length: 4,
        rate: "Рейтинг курса",
        creator: "Имя создателя",
        price: "Цена курса",
        created_at: "Дата создания курса",
      },
    ],
  },
];

export default BRANCHES;
